#!/bin/bash


if [ -z $1 ]; then
  echo "No env given, using activated env"
else
  if [ -z $2 ]; then
    echo "No stages given, assuming 2020"
    module load Stages/2020 GCC/10.3.0 Python/3.8.5 OpenMPI/4.1.1\
         mpi4py/3.0.3-Python-3.8.5 CUDA/11.3 cuDNN/8.2.1.32-CUDA-11.3&> /dev/null
  else
    echo "Stages given, assuming 2022"
    module load Stages/2022 GCC/11.2.0 Python/3.9.6 OpenMPI/4.1.2 \
         mpi4py/3.1.3 CUDA/11.5 cuDNN/8.3.1.22-CUDA-11.5 &> /dev/null
  fi
  source $HOME/envs/$1/bin/activate
fi

echo "ferminet path, jax version, jaxlib version, numpy version"
python -c "import ferminet, jax, jaxlib, numpy; \
				print(ferminet.__path__);\
				print(jax.__version__);\
				print(jaxlib.__version__);\
        print(numpy.__version__)"
